"""Retain every started attempt; do not turn planned/unstarted trials into failures."""
from pathlib import Path
import hashlib,json
from collections import Counter
b=Path('/home/nvidia/sim/rosclaw-robotics-lab/.runtime/v04');home=b.parents[2]
pilots=['l04pa01','l04pa02','l04pb01','l04pc01','l04pc02','l04pc03','l04pd01','l04qa03','l04qa04','l04qd05','l04qc06','l04qc07','l04qb08']
first=['l04fa01','l04fa02','l04fa03','l04fb01'];second=['l04ga01','l04ga02','l04ga03'];third=['l04ha01','l04ha02','l04ha03','l04hb01','l04hb02','l04hb03','l04hc01'];final=[t['id'] for t in json.loads((b/'formal4/protocol.json').read_text())['trials']];compat=['l04c01','l04oldc02']
notes={'l04pa01':'Source/build mismatch; physical sequence completed but acceptance FAIL','l04pa02':'Historical PASS under old cropped-ROI classifier; CLEAR superseded by boundary reanalysis, not final evidence','l04pb01':'Pilot obstacle detected; second gain 1 cell does not count as active observation success','l04pc01':'Historical physical PASS, intended occlusion condition FAIL: first view already 97.9%; old CLEAR superseded','l04pc02':'AMCL double-type startup failure; no Native task','l04qa03':'Actual path previews exceeded old startup readiness; no Native task','l04qa04':'Return proposal expired before dispatch; canonical FAILED receipt retained','l04qd05':'Observation paths unsafe; computed return also unsafe; dispatch blocked, Memory incomplete, remains FAIL','l04fa03':'Actual full sweep rejected initial rotation; failed task retained','l04fb01':'Completed after parent supervisor pause; child PASS and cleanup 0; parent wrapper exit code not recovered'}
rows=[]
for group,ids in [('calibration',pilots),('first_frozen_interrupted',first),('second_frozen_interrupted',second),('third_frozen_interrupted',third),('final_frozen',final),('postmerge_compatibility',compat)]:
 for ident in ids:
  root=home/ident;p=root/'result.json'
  if not p.exists():
   rows.append({'attempt':ident,'group':group,'status':'RUNNING' if root.exists() else 'NOT_STARTED'});continue
  r=json.loads(p.read_text());freeze=json.loads((root/'native/source-freeze.json').read_text()) if (root/'native/source-freeze.json').exists() else {};a=json.loads((root/'acceptance.json').read_text()) if (root/'acceptance.json').exists() else {};s=a.get('loading_inspection',{})
  rows.append({'attempt':ident,'group':group,'status':r['status'],'acceptance_status':a.get('status'),'inspection_result':s.get('result'),'coverage_ratio':s.get('coverage_ratio'),'views':a.get('observation_views'),'independent_case':a.get('independent_case'),'lab_sha':freeze.get('git_sha'),'upstream_sha':r.get('upstream_source_sha') or freeze.get('rosclaw_upstream',{}).get('git_sha'),'native_build_sha':r.get('native_build_stamp',freeze.get('native_build_stamp',{})).get('commit'),'cleanup_exit_code':r.get('cleanup_exit_code'),'native_exit_code':r.get('native_exit_code'),'manual_interventions':r.get('manual_interventions',[]),'note':notes.get(ident),'result_sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'started_wall_time':r.get('started_wall_time'),'finished_wall_time':r.get('finished_wall_time')})
out={'scope':'All started Native/startup engineering attempts. Historical raw acceptance remains unchanged; superseded claims explicitly noted. Planned unstarted cases are not counted as executed failures. P0 environment/control ledger separate.','groups':{g:dict(Counter(r['status'] for r in rows if r['group']==g)) for g in ('calibration','first_frozen_interrupted','second_frozen_interrupted','third_frozen_interrupted','final_frozen','postmerge_compatibility')},'attempts':rows};out['current_frozen_source_loading_outcomes']=dict(Counter(r['status'] for r in rows if r.get('lab_sha')==json.loads((b/'formal4/protocol.json').read_text())['lab_commit'] and r['group']!='postmerge_compatibility'));(b/'all-attempt-ledger.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n');print(json.dumps(out['groups']))
